name: Deploy to EC2

on:
  push:
    branches:
      - main # or your deployment branch

jobs:
  deploy:
    runs-on: self-hosted # Use self-hosted runner on Amazon Linux

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            pm2 stop all || true
            rm -rf ${{ secrets.EC2_APP_DIR }}
            mkdir -p ${{ secrets.EC2_APP_DIR }}
          EOF

          scp -i private_key.pem -r ./* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.EC2_APP_DIR }}

          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ${{ secrets.EC2_APP_DIR }}
            npm install
            pm2 start app.js --name node-app || pm2 restart node-app
            pm2 save
          EOF
